### ISSUE TITLE
Sensor de Temperatura del motor

### ISSUE THREAD

**Issue by Neximar** [ULAnux/mathematica#41]
Actuador o valvula IAC 

Funcion: 
La válvula IAC  se encarga de proporcionar el aire necesario para el funcionamiento en marcha minima del motor. Estando el motor en marcha lenta, la cantidad de aire que pasa por la mariposa de aceleración es muy poco y la válvula IAC proporciona el resto del aire por un conducto aparte del mismo cuerpo de aceleracion. 

El sensor de temperatura del refrigerante es un termistor (una resistencia que varía el valor de su salida de tensión de acuerdo con los cambios de temperatura.). El cambio en los valores de resistencia afectarán directamente a la señal de voltaje del sensor térmico de agua. A medida que disminuye la temperatura del sensor, el valore de resistencia aumentará. A medida que aumenta la temperatura del sensor, los valores de la resistencia disminuirán. 
El sensor de la temperatura del refrigerante permite que el equipo de control de motores sepa cuál es la temperatura del motor mediante la recopilación de información de la temperatura del refrigerante del motor. 
Normalmente el sensor de temperatura del refrigerante se encuentra cerca del termostato, a veces el equipo utiliza el mismo sensor para el funcionamiento del medidor de la temperatura en su panel de instrumentos, dependiendo del coche marca y modelo. 

Algunos problemas asociados a un sensor de temperatura de refrigerante defectuoso son:

Consumo excesivo de combustible.
Mínimo de motor inestable.
Problemas en el arranque en frió.
Problemas en el arranque ya con el motor a temperatura optima de funcionamiento(caliente).
Problemas con la activación de los abanicos eléctricos de refrigeración.

**Comment by jacintodavila** [comment]
Podrías darle un poco más de estructura y agregarlo como pull request, por favor. Gracias.
